 # PREVISAO DE RISCO DE CREDITOS COM NAIVE BAYES



In [14]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB

In [2]:
risco_credito = pd.read_csv('../Dados/Bases_de_dados/risco_credito.csv')

In [3]:
risco_credito

historia divida garantias     renda     risco
0           ruim   alta   nenhuma      0_15      alto
1   desconhecida   alta   nenhuma     15_35      alto
2   desconhecida  baixa   nenhuma     15_35  moderado
3   desconhecida  baixa   nenhuma  acima_35      alto
4   desconhecida  baixa   nenhuma  acima_35     baixo
5   desconhecida  baixa  adequada  acima_35     baixo
6           ruim  baixa   nenhuma      0_15      alto
7           ruim  baixa  adequada  acima_35  moderado
8            boa  baixa   nenhuma  acima_35     baixo
9            boa   alta  adequada  acima_35     baixo
10           boa   alta   nenhuma      0_15      alto
11           boa   alta   nenhuma     15_35  moderado
12           boa   alta   nenhuma  acima_35     baixo
13          ruim   alta   nenhuma     15_35      alto

In [4]:
# Separacao de variaveis
X_risco_credito = risco_credito.iloc[:, 0:4].values # variavel X

In [5]:
X_risco_credito

array([['ruim', 'alta', 'nenhuma', '0_15'],
       ['desconhecida', 'alta', 'nenhuma', '15_35'],
       ['desconhecida', 'baixa', 'nenhuma', '15_35'],
       ['desconhecida', 'baixa', 'nenhuma', 'acima_35'],
       ['desconhecida', 'baixa', 'nenhuma', 'acima_35'],
       ['desconhecida', 'baixa', 'adequada', 'acima_35'],
       ['ruim', 'baixa', 'nenhuma', '0_15'],
       ['ruim', 'baixa', 'adequada', 'acima_35'],
       ['boa', 'baixa', 'nenhuma', 'acima_35'],
       ['boa', 'alta', 'adequada', 'acima_35'],
       ['boa', 'alta', 'nenhuma', '0_15'],
       ['boa', 'alta', 'nenhuma', '15_35'],
       ['boa', 'alta', 'nenhuma', 'acima_35'],
       ['ruim', 'alta', 'nenhuma', '15_35']], dtype=object)

In [6]:
y_risco_credito = risco_credito.iloc[:, 4].values # variavel y

In [7]:
y_risco_credito

array(['alto', 'alto', 'moderado', 'alto', 'baixo', 'baixo', 'alto',
       'moderado', 'baixo', 'baixo', 'alto', 'moderado', 'baixo', 'alto'],
      dtype=object)

In [8]:
# Conversao de strings e numericos com LABELENCODER
from sklearn.preprocessing import LabelEncoder
variavel1_historia = LabelEncoder()
variavel2_divida = LabelEncoder()
variavel3_garantias = LabelEncoder()
variavel4_renda = LabelEncoder()

In [9]:
# Aplicar os processamentos
X_risco_credito[:,0] = variavel1_historia.fit_transform(X_risco_credito[:,0])
X_risco_credito[:,1] = variavel2_divida.fit_transform(X_risco_credito[:,1])
X_risco_credito[:,2] = variavel3_garantias.fit_transform(X_risco_credito[:,2])
X_risco_credito[:,3] = variavel4_renda.fit_transform(X_risco_credito[:,3])


In [10]:
X_risco_credito

array([[2, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 2],
       [1, 1, 0, 2],
       [2, 1, 1, 0],
       [2, 1, 0, 2],
       [0, 1, 1, 2],
       [0, 0, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 2],
       [2, 0, 1, 1]], dtype=object)

In [11]:
import pickle
with open('risco_credito.pkl', 'wb') as f:
    pickle.dump([X_risco_credito, y_risco_credito],f)

In [15]:
#TREINAR O MODELO
naive_risco_credito = GaussianNB() 
naive_risco_credito.fit(X_risco_credito, y_risco_credito)

GaussianNB()

In [21]:
# Historia boa (0), divida alta(0), garantias nenhuma(1), renda > 35(2)
# Historia ruim (2), divida alta(1), garantias adequadas (0), renda <15(0)

previsao = naive_risco_credito.predict([[0,0,1,2],[2,1,0,0]])

In [22]:
previsao

array(['baixo', 'moderado'], dtype='<U8')

In [23]:
naive_risco_credito.classes_

array(['alto', 'baixo', 'moderado'], dtype='<U8')

In [26]:
naive_risco_credito.class_count_

array([6., 5., 3.])

In [28]:
naive_risco_credito.class_prior_

array([0.42857143, 0.35714286, 0.21428571])